# Generated by Django 2.2.7 on 2020-04-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='item_imgs')),
                ('category', models.CharField(choices=[('Vegetable', 'Vegetable'), ('Fruit', 'Fruit'), ('Dairy', 'Dairy'), ('Meat', 'Meat'), ('Sugar', 'Sugar'), ('Bread', 'Bread'), ('Pre-Packed', 'Pre-Packed'), ('Can', 'Can'), ('Misc', 'Misc')], default='Misc', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3000)),
                ('batch', models.IntegerField(null=True)),
                ('desc', models.TextField(default="One of PyShop's item", max_length=300)),
            ],
        ),
    ]
