# Generated by Django 2.2.7 on 2020-04-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200414_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='batch',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='TEST', upload_to='item_imgs'),
        ),
    ]
