# Generated by Django 2.2.7 on 2020-04-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200414_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='no_image.jpg', upload_to='item_imgs'),
        ),
    ]
